apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-37n6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-37n6
    app.kubernetes.io/part-of: integ-app-jjnw
  name: hacbs-test-project-37n6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-37n6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-37n6
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-urer-tenant/integ-app-jjnw/hacbs-test-project-37n6@sha256:1d95ce696dcaf1bcfd255f0c36c471136cb6c75a17588e376f2cb2af391bfe8a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
